# -*- coding: utf-8 -*-
"""DS_3000.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJ0cD-lb7o6XPCasoNJa52AGLMl7C4TT
"""

# Block-1
# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Import DS3000-Final Folder
import os
os.listdir('/content/drive/MyDrive/DS3000-Final')

import pandas as pd

# Loads the "ML-ready" charging-station dataset
df_stations = pd.read_csv('/content/drive/MyDrive/DS3000-Final/charging_station_ml.csv')
df_stations.head()

# Block-2
# Overview of dataset columns, types, and missing values
df_stations.info()

# Basic statistics for numerical columns
df_stations.describe()

# Count of missing values per column
df_stations.isnull().sum()

# Block-3
# Filling errors/missing values in data-set
# Fill tiny missing 'fast_port_share' with median
df_stations['fast_port_share'].fillna(df_stations['fast_port_share'].median(), inplace=True)

# Fill 'max_power_kw' and 'median_power_kw' with median
df_stations['max_power_kw'].fillna(df_stations['max_power_kw'].median(), inplace=True)
df_stations['median_power_kw'].fillna(df_stations['median_power_kw'].median(), inplace=True)

# Verify missing values were handled
df_stations.isnull().sum()

# Block-4
# Feature engineering for total power esitmates and Fast-DC ratio
# Total estimated station power
df_stations['total_station_power'] = df_stations['station_count'] * df_stations['median_power_kw']

# Fast DC ratio
df_stations['fast_dc_ratio'] = df_stations['dc_fast_station_count'] / df_stations['station_count']

# Block-5
# Loading & Cleaning EV_models data-set
df_ev = pd.read_csv('/content/drive/MyDrive/DS3000-Final/ev_models.csv')
df_ev.head()  # peek at first few rows
df_ev.info()  # check column types and missing values

# Mapping for battery size to vehicle size (Scale battery size with vehicle size)
body_battery_map = {
    'SUV': 75,
    'Sedan': 60,
    'Hatchback': 50,
    'Truck': 100
}

df_ev['battery_kWh_est'] = df_ev['body_style'].map(body_battery_map)

# Block-6
# Clean / standardize body style values

# Define normalized category mapping
# Body-type generalizations
body_style_map = {
    'Sedan': 'Sedan',
    'Sedan/Wagon': 'Sedan',
    'Sedan/SUV': 'SUV',           # Hybrid category → choose dominant
    'Liftback': 'Sedan',          # Liftback typically sedan-like

    'Hatchback': 'Hatchback',
    'City car': 'Hatchback',      # Small EV city cars behave similarly

    'SUV': 'SUV',
    'SUV (3-row)': 'SUV',
    'SUV Coupe': 'SUV',
    'Crossover': 'Crossover',     # Keep separate for now
    'Pickup/SUV': 'Pickup',       # Mixed → treat as pickup

    'Pickup': 'Pickup',

    'Van': 'Van',
    'MPV': 'Van',                 # MPV = multi-purpose van

    'Coupe': 'Coupe',
    'Wagon': 'Wagon',
    'Shooting Brake': 'Wagon'     # Shooting brake = sporty wagon
}

# Apply mapping
df_ev['body_style_clean'] = df_ev['body_style'].map(body_style_map)

# Check results
df_ev['body_style_clean'].value_counts(dropna=False)

# Block-7
# Create battery estimates by standardized body style

battery_mapping = {
    'Sedan': 65,
    'SUV': 85,
    'Crossover': 75,
    'Hatchback': 50,
    'Pickup': 110,
    'Van': 90,
    'Wagon': 70,
    'Coupe': 75
}

# Apply mapping
df_ev['battery_kWh_est'] = df_ev['body_style_clean'].map(battery_mapping)

# Fill any unmapped ones with median
df_ev['battery_kWh_est'].fillna(df_ev['battery_kWh_est'].median(), inplace=True)

# Verify no missing values
df_ev['battery_kWh_est'].isnull().sum()

# Block-8
# Load country + world summary datasets

df_country = pd.read_csv('/content/drive/MyDrive/DS3000-Final/country_summary.csv')
df_world = pd.read_csv('/content/drive/MyDrive/DS3000-Final/world_summary.csv')

df_country.head(), df_country.info(), df_world.head(), df_world.info()

# Block-9
# Clean world_summary missing values + engineer features

# Fill missing power values with median value (safe because distribution is skewed)
df_world['max_power_kw'] = df_world['max_power_kw'].fillna(df_world['max_power_kw'].median())
df_world['median_power_kw'] = df_world['median_power_kw'].fillna(df_world['median_power_kw'].median())


# Feature Engineering
df_world['total_station_power'] = df_world['station_count'] * df_world['median_power_kw']
df_world['fast_dc_ratio'] = df_world['dc_fast_station_count'] / df_world['station_count']

# Verify
df_world.isnull().sum()

# Block-10
#Load and inspect charging_station dataset for cleaning

df_station = pd.read_csv('/content/drive/MyDrive/DS3000-Final/charging_station.csv')

print("Shape:", df_station.shape)
df_station.head()
df_station.info()

# Block-11
# Clean charging_station dataset (corrected version)

# 1. Fill missing power_kw using median power for each power_class
# Compute median power per class
class_medians = df_station.groupby('power_class')['power_kw'].median()

# Function to fill missing values using class median
def fill_power_kw(row):
    if pd.isna(row['power_kw']):
        cls = row['power_class']
        # If class exists in the median map, use it; otherwise fallback to global median
        return class_medians.get(cls, df_station['power_kw'].median())
    return row['power_kw']

df_station['power_kw'] = df_station.apply(fill_power_kw, axis=1)

# 2. Create power tier labels (same as before)
def classify_power(power):
    if power >= 150:
        return 'Ultra DC'
    elif power >= 50:
        return 'Fast DC'
    else:
        return 'Level 2'

df_station['power_tier'] = df_station['power_kw'].apply(classify_power)

# 3. Engineer total capacity feature
df_station['total_power_kw'] = df_station['power_kw'] * df_station['ports']

# Verify results
df_station[['power_kw', 'power_class', 'power_tier', 'ports', 'total_power_kw']].head()
df_station['power_tier'].value_counts()

# Block-12
# Merge station-level and world-level data-sets

# Ensure country_code fields match formatting
df_station['country_code'] = df_station['country_code'].str.upper()
df_world['country_code'] = df_world['country_code'].str.upper()

# Merge on country_code
df_merged = df_station.merge(
    df_world,
    on='country_code',
    how='left',
    suffixes=('_station', '_country')
)

print("Merged Shape:", df_merged.shape)
df_merged.head()

# Block-13
# Engineer relative infrastructure features

# Share of total national station power
df_merged['station_power_share'] = df_merged['total_power_kw'] / df_merged['total_station_power']

# Ports relative to national average
df_merged['avg_ports_per_station'] = df_merged['port_count'] / df_merged['station_count']
df_merged['ports_vs_country_avg'] = df_merged['ports'] - df_merged['avg_ports_per_station']

# Power percentile flag
df_merged['is_above_median_power'] = df_merged['power_kw'] > df_merged['median_power_kw']

# Fast DC vs country average deviation
df_merged['fast_dc_vs_country'] = df_merged['is_fast_dc'].astype(int) - df_merged['fast_dc_ratio']

df_merged.head()

# Block-14
# Inspect EV dataset for region fields (Mostly a double-check from earlier)

print("Shape:", df_ev.shape)
df_ev.info()
df_ev.head()
df_ev.columns

# Block-15
# Prepare EV dataset for merging with main, cleaned data-set

# 1. Split multi-region entries into separate rows
df_ev_expanded = df_ev.assign(
    market_regions=df_ev['market_regions'].str.split(',')
).explode('market_regions')

# 2. Strip whitespace from region names
df_ev_expanded['market_regions'] = df_ev_expanded['market_regions'].str.strip()

# 3. Keep only necessary columns
df_ev_model = df_ev_expanded[['make', 'model', 'body_style_clean', 'battery_kWh_est', 'market_regions']]

# 4. Verify
print("Shape after expanding:", df_ev_model.shape)
df_ev_model.head()

# Block-16
# Mapping global regions to countires
# Includes mapping EV models based on country/regional availablity to local regions
# Region mapping
region_to_country = {
    "US": ["US"],
    "EU": ["AD","AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GB","GR","HU","IE","IT","LI","LT","LU","LV","MC","MT","NL","NO","PL","PT","RO","SE","SI","SK"],
    "UK": ["GB"],
    "ME": ["AL","BA","MK","RS","ME","XK","HR","GR","SI"],  # Example for “Middle Europe / Balkans”
    "CN": ["CN"],
    "Global (US/EU/UK/ME)": ["US","AD","AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GB","GR","HU","IE","IT","LI","LT","LU","LV","MC","MT","NL","NO","PL","PT","RO","SE","SI","AL","BA","MK","RS","ME","XK","HR"],
    "Global (US/EU/UK/ME/CN)": ["US","AD","AT","BE","BG","CH","CY","CZ","DE","DK","EE","ES","FI","FR","GB","GR","HU","IE","IT","LI","LT","LU","LV","MC","MT","NL","NO","PL","PT","RO","SE","SI","AL","BA","MK","RS","ME","XK","HR","CN"],
    "US (limited)": ["US"]
}
# Map EV rows to country codes
df_ev_model['country_codes'] = df_ev_model['market_regions'].map(region_to_country)

# Explode so each EV-country combination is its own row
df_ev_country = df_ev_model.explode('country_codes').rename(columns={'country_codes':'country_code'})

# Verify
print("Shape after mapping to countries:", df_ev_country.shape)
df_ev_country.head()

# Block-17
# Merge stations data-set with EVs by country data-set
df_station_ev = df_station.merge(
    df_ev_country,
    on='country_code',
    how='left'   # keep all stations, even if some have no EVs techincally
)

# Verify the merge
print("Shape after merging stations with EVs:", df_station_ev.shape)
df_station_ev.head()

# Block-18
# Use the correct merged DataFrame
# This assumes EV info per station with country exploded
# Normal if this takes a while to load
station_agg = df_station_ev.groupby('id').agg(
    total_evs = ('model', 'count'),
    avg_battery = ('battery_kWh_est', 'mean'),
    body_style_counts = ('body_style_clean', lambda x: x.value_counts().to_dict())
).reset_index()

# Expand the dictionary of body style counts into separate columns
body_style_df = station_agg['body_style_counts'].apply(pd.Series).fillna(0)

# Merge expanded body style counts back into main DataFrame
station_agg_final = pd.concat([station_agg.drop(columns='body_style_counts'), body_style_df], axis=1)

# Optional: convert counts to integers
station_agg_final[body_style_df.columns] = station_agg_final[body_style_df.columns].astype(int)

# Verify the final DataFrame
print("Shape after aggregating EV info per station:", station_agg_final.shape)
station_agg_final.head()

# Block-19
#Final station summary with percentages and flags
# Merge back descriptive station info (name, city, state, etc.) into main data-set
station_summary = station_agg_final.merge(
    df_station[['id','name','city','state_province','country_code','latitude','longitude','ports','power_kw','power_class','is_fast_dc','power_tier','total_power_kw']],
    on='id',
    how='left'
)

# Reorder columns for clarity
cols_order = [
    'id','name','city','state_province','country_code','latitude','longitude',
    'ports','power_kw','power_class','is_fast_dc','power_tier','total_power_kw',
    'total_evs','avg_battery'
] + [col for col in station_agg_final.columns if col not in ['id','total_evs','avg_battery']]
station_summary = station_summary[cols_order]

# Compute percentage of each body style per station
body_style_cols = [col for col in station_agg_final.columns if col not in ['id','total_evs','avg_battery']]
for col in body_style_cols:
    station_summary[f'{col}_pct'] = station_summary[col] / station_summary['total_evs'] * 100

# Optional flags
station_summary['mostly_fast_dc'] = station_summary['is_fast_dc'] & (station_summary['total_evs'] >= 5)
station_summary['high_ev_count'] = station_summary['total_evs'] >= 10

# Verify final DataFrame
print("Shape of final station summary:", station_summary.shape)
station_summary.head()

# Block-20: Handle remaining missing values in EV density and battery features
# Goal: Make sure station_summary has NO NaNs in key engineered columns
#       (avg_battery and the EV body-style percentage columns),
#       so models can safely train without errors.

# 1. Inspect current NaN counts in the affected columns
pct_cols = ['SUV_pct', 'Pickup_pct', 'Sedan_pct', 'Van_pct']
print("NaNs BEFORE fix:\n")
print(station_summary[['avg_battery'] + pct_cols].isna().sum())

# 2. Fix:
#    - For stations with no EV data, set percentage columns to 0
#    - Impute avg_battery with the median battery size across all stations
station_summary[pct_cols] = station_summary[pct_cols].fillna(0)
station_summary['avg_battery'] = station_summary['avg_battery'].fillna(
    station_summary['avg_battery'].median()
)

# 3. Verify that NaNs are gone
print("\nNaNs AFTER fix:\n")
print(station_summary[['avg_battery'] + pct_cols].isna().sum())

# Block-21: Simplify categorical features and create an ML-ready encoded dataset
# Goal: Drop high-cardinality location/name columns and one-hot encode the
#       low-cardinality power-related categoricals for use in regression / tree models.

# 1. Start from the cleaned station_summary
df_model = station_summary.copy()

# 2. Drop non-predictive / high-cardinality identifier/location columns
drop_cols = ['name', 'city', 'state_province', 'country_code']
df_model = df_model.drop(columns=drop_cols)

print("Columns after dropping high-cardinality/non-predictive fields:\n")
print(df_model.columns)

# 3. Define categorical columns to one-hot encode
categorical_cols = ['power_class', 'power_tier']

print("\nUnique category counts BEFORE encoding:")
for col in categorical_cols:
    print(f"  {col}: {df_model[col].nunique()} unique values")

# 4. One-hot encode power_class and power_tier
df_model_encoded = pd.get_dummies(
    df_model,
    columns=categorical_cols,
    drop_first=True  # avoid dummy variable trap
)

# 5. Sanity check: there should be no object dtypes left
print("\nDtype summary AFTER encoding:")
print(df_model_encoded.dtypes.value_counts())

# 6. (Optional) preview the encoded data
df_model_encoded.head()

# 7. Export the ML-ready encoded dataset
df_model_encoded.to_csv('station_summary_model_encoded.csv', index=False)
print("\nSaved encoded dataset as 'station_summary_model_encoded.csv'")

# Block-22
# Interactive map-visualization of EV stations globally
# Be careful with keeping this output displayed, it takes up a significant amount of system resources, and I have had problems with saving the file while keeping displayed

import folium
from folium.plugins import MarkerCluster

# Create a map centered roughly at the geographic center of your dataset
map_center = [station_summary['latitude'].mean(), station_summary['longitude'].mean()]
ev_map = folium.Map(location=map_center, zoom_start=4)

# Cluster markers for readability
marker_cluster = MarkerCluster().add_to(ev_map)

# Choose a metric to color markers (e.g., total EVs)
for _, row in station_summary.iterrows():
    # Choose color based on total EVs
    if row['total_evs'] >= 20:
        color = 'darkred'
    elif row['total_evs'] >= 10:
        color = 'red'
    elif row['total_evs'] >= 5:
        color = 'orange'
    else:
        color = 'green'

    # Popup info
    popup_text = f"""
    <b>{row['name']}</b><br>
    {row['city']}, {row['state_province']}<br>
    Total EVs: {row['total_evs']}<br>
    Avg Battery: {row['avg_battery']:.1f} kWh<br>
    SUV: {row.get('SUV',0)}, Sedan: {row.get('Sedan',0)}, Pickup: {row.get('Pickup',0)}, Van: {row.get('Van',0)}
    """

    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=5 + row['total_evs']*0.2,   # size proportional to total EVs
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7,
        popup=folium.Popup(popup_text, max_width=300)
    ).add_to(marker_cluster)

# Display the map
ev_map

# Block-23
# Additional visulizations and graphics
import matplotlib.pyplot as plt
import seaborn as sns

# Histogram of total EVs per station
plt.figure(figsize=(10,6))
sns.histplot(station_summary['total_evs'], bins=30, kde=False, color='teal')
plt.title("Distribution of Total EVs per Station")
plt.xlabel("Total EVs")
plt.ylabel("Number of Stations")
plt.show()


plt.figure(figsize=(10,6))
sns.histplot(station_summary['avg_battery'], bins=30, kde=True, color='orange')
plt.title("Distribution of Average Battery Size per Station")
plt.xlabel("Average Battery (kWh)")
plt.ylabel("Number of Stations")
plt.show()

# Sum all body style counts
body_styles = ['SUV', 'Sedan', 'Pickup', 'Van']  # adjust based on your columns
body_style_totals = station_summary[body_styles].sum().sort_values(ascending=False)


plt.figure(figsize=(8,5))
sns.barplot(x=body_style_totals.index, y=body_style_totals.values, palette='muted')
plt.title("Total EVs by Body Style Across All Stations")
plt.ylabel("Number of EVs")
plt.show()


# Sum all body style counts
body_styles = ['SUV', 'Sedan', 'Pickup', 'Van']  # adjust based on your columns
body_style_totals = station_summary[body_styles].sum().sort_values(ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x=body_style_totals.index, y=body_style_totals.values, palette='muted')
plt.title("Total EVs by Body Style Across All Stations")
plt.ylabel("Number of EVs")
plt.show()


plt.figure(figsize=(10,6))
sns.boxplot(x='mostly_fast_dc', y='total_evs', data=station_summary)
plt.title("EV Counts by Station Type (Mostly Fast DC vs. Mostly AC)")
plt.xlabel("Mostly Fast DC")
plt.ylabel("Total EVs")
plt.show()

"""Key insights from cleaned data:

*   Most EV-charging stations average roughly 3.8 vechicles per station globally.
*   Most EV's have one of two standard battery sizes in (KWH).
*   EV-SUV's are a substantially more popular body style than Sedans (including coupes and hatches), Pickups or Vans.
*   Nearly all EV charging stations are comprised of majorly AC chargers, with a few Fast-DC or Ultra-DC ports.
*   Generally, larger stations (total kW), do support more EV's (higher EV-densities).

Data-Set Notes:
*   Relatively complete and comprehensive data-set (few missing or bad data entries).
*   Data is more limited from rural areas.
*   EV-Infrastructure varies greatly with country and geographical region.
*   Final cleaned data sets are: "station_summary.csv" & "station_agg_final.csv".
*   Most missing values were filled with median categorical values.
*   **SOME DATA-SETS AND GRAPHICS ARE SYSTEM-RESOURCE INTENSIVE AND MAY TAKE A WHILE TO LOAD/DISPLAY**

Notes for Model Creation:
*   Market for EV list can help give an idea of which EV's are being used in each region.
*   Total station power and number for ports, along with ratio of AC:Fast-DC can help give estimates of peak supply/capacity per station.
*   Very high correlation between battery capacity (kWh), body-style and charg-time (larger vehicles (mostly) mean larger batteries and longer charge times).
*   In map, darker coloured areas indicate higher EV-densities in the area around the station.












"""

# Block-24: Export and Share
# Goal:
#   - Export all datasets into organized folders
#   - Save visualizations separately for report use
#   - Ensure teammates can easily find all project files

import os
import matplotlib.pyplot as plt
import seaborn as sns

# --- Create folders if needed ---
os.makedirs('data', exist_ok=True)
os.makedirs('figures', exist_ok=True)

# --- Export datasets ---
station_agg_final.to_csv('data/station_agg_final.csv', index=False)
station_summary.to_csv('data/station_summary.csv', index=False)

# df_model_encoded should already be created in Block-YY
df_model_encoded.to_csv('data/station_summary_model_encoded.csv', index=False)

print("✓ Exported datasets to /data:")
print("  - data/station_agg_final.csv")
print("  - data/station_summary.csv")
print("  - data/station_summary_model_encoded.csv")

# --- Save key visualizations ---
plt.figure(figsize=(10, 6))
sns.histplot(station_summary['total_evs'], bins=30, kde=False, color='teal')
plt.title("Distribution of Total EVs per Station")
plt.xlabel("Total EVs")
plt.ylabel("Number of Stations")
plt.savefig('figures/total_evs_distribution.png')
plt.close()

plt.figure(figsize=(10, 6))
sns.histplot(station_summary['avg_battery'], bins=30, kde=True, color='orange')
plt.title("Distribution of Average Battery Size per Station")
plt.xlabel("Average Battery (kWh)")
plt.ylabel("Number of Stations")
plt.savefig('figures/avg_battery_distribution.png')
plt.close()

print("✓ Saved visualizations to /figures:")
print("  - figures/total_evs_distribution.png")
print("  - figures/avg_battery_distribution.png")